### PR TITLE
Statamic 4 and Laravel 10 support

### PR DESCRIPTION
**Pull request by royvanv**
Fixes issue #15.

### CODE REVIEW

**Comment by royvanv** [comment]
@octoper Could you please review this pull request?

**Comment by octoper** [comment]
Hello @royvanv!
Thank you for the PR!
I'm not using Statamic anymore and because I have a very limited time I can't support it, so I put a looking for maintainers on the repo, if you are interested on helping maintaining it you are welcome and you can reach me via email me@octoper.me

**Comment by royvanv** [comment]
Thanks for merging.

Unfortunately v2.0.0 still only lists `statamic/cms: ^3.3` as dependency. See the Packagist page for version 2.0.0: https://packagist.org/packages/octoper/statamic-blade-components#2.0.0

**Comment by octoper** [comment]
Going to take some look and today, thank's for reporting that!

**Pull request merged**
