### PR TITLE
Laravel 9 support.

### PR DESCRIPTION
**Pull request by royvanv**

### CODE REVIEW

**Comment by royvanv** [comment]
@octoper Could you please review this PR?

**Comment by octoper** [comment]
I haven't been able to test it yet I will try to do it tonight

**Comment by royvanv** [comment]
It's been over a month now.

Also, Laravel 7 is end of life now. I would suggest dropping support for it, as well. If you agree I will update this PR.

**Review by octoper — APPROVED** [review]

**Comment by octoper** [comment]
Thank you!

**Pull request merged**
